"""No-training diagnostic measurements; never issues a performance certificate."""
from __future__ import annotations

from dataclasses import replace
from pathlib import Path
import csv
import hashlib
import json
import sys
import numpy as np
import torch

from ..provenance import write_json, hardware_environment, json_safe
from .config import AdaptiveConfig
from .data import dataset
from .models import Components
from .evaluation import measured
from .acceptance import _successful as successful_run

REVISION = 'v67-limited-fix-1'
BRANCHES = ('C', 'H_S', 'H_P', 'H_SP')


def digest_file(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def read_settings(research):
    research = Path(research).resolve()
    settings = json.loads((research / 'configuration.json').read_text())
    torch.set_num_threads(int(settings['torch_threads']))
    initialize_timing_runtime()
    return research, settings, AdaptiveConfig.from_dict(settings['solver'])


def initialize_timing_runtime():
    # Load an existing optional library before recording hardware pools. Never
    # compile or autotune; per-kernel native_threads remains the saved config.
    from ..native_stencil import native_available
    return native_available()


def safe_output(output, research):
    output, research = Path(output).resolve(), Path(research).resolve()
    if output == research or research in output.parents or output in research.parents:
        raise ValueError('Output must be separate from the read-only original research tree')
    output.mkdir(parents=True, exist_ok=True)
    return output


def vector_digest(value):
    return hashlib.sha256(np.asarray(value, dtype=np.float64).tobytes()).hexdigest()


def diagnostic_cases(research, settings, split='smoke', limit=None, sizes=None):
    """Verify exact stored A specifications, explicitly qualify reconstructed RHS."""
    if split == 'smoke':
        examples = dataset(sizes or [15], per_size=2, seed=int(settings['seed']) + 300003)
        scope = 'new small diagnostic set; smoke only; no performance certification'
        verification = 'new diagnostic cases, shared A/b/x0 across all arms'
    else:
        if sizes:
            raise ValueError('--sizes applies only to a new smoke set; never relabel a changed audit')
        offset = 100001 if split == 'tune' else 200002
        examples = dataset(settings[split + '_sizes'], settings[split + '_per_size'],
                           int(settings['seed']) + offset)
        stored = json.loads((Path(research) / 'split_manifest.json').read_text())['splits'][split]
        generated = [e.manifest() for e in examples]
        if json_safe(generated) != json_safe(stored):
            raise ValueError('Reconstructed case specification/operator digest differs from original manifest')
        scope = ('diagnostic re-evaluation of previously inspected audit' if split == 'audit'
                 else 'diagnostic re-evaluation of original tuning split')
        verification = ('all stored case specifications and A digests verified; RHS regenerated by original '
                        'unchanged deterministic generator/seed; original has no independent b digest')
    if limit is not None:
        if limit < 1:
            raise ValueError('--limit must be positive')
        examples = examples[:limit]
    records = [dict(e.manifest(), rhs_digest=vector_digest(e.b),
                    x0_digest=vector_digest(np.zeros_like(e.b)), exact_digest=vector_digest(e.exact))
               for e in examples]
    return examples, dict(split=split, scope=scope, verification=verification, cases=records,
                          independent_certification_evidence=False)


def forced_config(cfg, branch):
    if branch not in BRANCHES:
        raise ValueError('unknown explicit branch')
    return replace(cfg, branch=branch, mode='classical' if branch == 'C' else 'research',
                   use_smoother=branch in ('H_S', 'H_SP'), use_transfer=branch in ('H_P', 'H_SP'),
                   spatial=False, gate_mode='open')


def _success(runs, cfg):
    return bool(runs) and all(successful_run(r, cfg) for r in runs)


def _median(runs, key, default=0.):
    values = [r.get(key, default) for r in runs]
    if not values or any(v is None or not np.isfinite(v) for v in values): return None
    return float(np.median(values))


def aggregate_comparison(rows, arms):
    """Failure runtimes stay observable, but never become time-to-tolerance."""
    table, summary = [], {}
    for arm, spec in arms.items():
        ratios, common, new, rescued, both, successes, neural_cases = [], [], [], [], [], [], []
        for row in rows:
            case = row['example']['name']; runs = row['runs'][arm]; cr = row['runs']['classical']
            cs, ns = _success(cr, arms['classical']['config']), _success(runs, spec['config'])
            if ns: successes.append(case)
            if cs and ns: common.append(case)
            if cs and not ns: new.append(case)
            if ns and not cs: rescued.append(case)
            if not cs and not ns: both.append(case)
            elapsed = _median(runs, 'wall_seconds'); classical_time = _median(cr, 'wall_seconds')
            valid_times = all(isinstance(r.get('wall_seconds'), (float, int)) and
                              np.isfinite(r['wall_seconds']) and r['wall_seconds'] > 0 for r in cr + runs)
            speedup = classical_time / elapsed if cs and ns and valid_times else None
            if speedup is not None: ratios.append(speedup)
            counters = {}
            for run in runs:
                for container in ('stats', 'setup_stats'):
                    for key, value in run.get(container, {}).items():
                        if isinstance(value, (float, int)) and not isinstance(value, bool):
                            counters[key] = counters.get(key, 0) + value
            numerical = counters.get('neural_apply_calls', 0) + counters.get('learned_transfer_apply_calls', 0)
            if numerical: neural_cases.append(case)
            branches = sorted({b for run in runs for b in run.get('actually_executed_branches', [])})
            p_banks = sorted({str(run.get('p_bank', 'unreported')) for run in runs})
            record = dict(case_id=case, n=row['example']['case']['n'], arm=arm,
                checkpoint_id=spec['checkpoint_id'], branch=spec['branch'], experiment=spec['scope'],
                successful_repeats=sum(successful_run(r, spec['config']) for r in runs), repeats=len(runs), success=ns,
                classical_success=cs, classical_cycles=_median(cr, 'cycles'), candidate_cycles=_median(runs, 'cycles'),
                attempted_cycles=_median(runs, 'executed_cycles'), final_residual=_median(runs, 'final_true_residual'),
                relative_residual=_median(runs, 'relative_residual'), solution_error=_median(runs, 'relative_solution_error'),
                setup_seconds=_median(runs, 'setup_seconds'), solve_seconds=_median(runs, 'solve_seconds'),
                total_seconds=elapsed, successful_time_to_tolerance_seconds=elapsed if ns and valid_times else None,
                speedup_vs_classical=speedup, speedup_vs_incumbent=None,
                nn_forward=counters.get('smoother_nn_calls', 0) + counters.get('transfer_nn_calls', 0),
                total_nn_forward=counters.get('nn_forward_calls', 0),
                controller_nn_forward=counters.get('controller_nn_calls', 0),
                smoother_nn_forward=counters.get('smoother_nn_calls', 0),
                transfer_nn_forward=counters.get('transfer_nn_calls', 0),
                learned_operator_application=numerical, controller_calls=counters.get('controller_calls', 0),
                detector_calls=counters.get('detector_calls', 0),
                attempted_neural=counters.get('attempted_neural_cycles', 0),
                accepted_neural=counters.get('accepted_neural_cycles', 0),
                rejected_neural=counters.get('rejected_neural_cycles', 0),
                fallback=counters.get('fallback_cycles', counters.get('classical_recovery_cycles', 0)),
                classical_strategy=spec['config'].mg.strategy_name, actual_p_bank=p_banks,
                actually_executed_branch=branches, counters_sum_all_repeats=counters)
            table.append(record)
        gm = float(np.exp(np.log(ratios).mean())) if ratios else None
        if ratios:
            rng = np.random.default_rng(93); logs = np.log(ratios)
            ci = np.quantile(np.exp(rng.choice(logs, (2000, len(logs)), replace=True).mean(1)), [.025, .975]).tolist()
        else: ci = [None, None]
        summary[arm] = dict(successes=len(successes), total=len(rows), common_successes=len(common),
            new_failures=len(new), rescued_cases=len(rescued), both_failed=len(both),
            new_failure_case_ids=new, rescued_case_ids=rescued, both_failed_case_ids=both,
            geometric_speedup_vs_classical=gm, speedup_vs_incumbent=None, speedup_ci95=ci,
            actual_neural_case_ids=neural_cases, stage_promoted=False,
            direct_classical_speedup_observed=bool(gm is not None and gm > 1),
            final_time_improvement_certified=False)
    return dict(summary=summary, table=table,
                repeat_failure_policy='every repeat must succeed; failed runtime is not time-to-tolerance',
                counter_scope='sum over measured repeats, includes rejected trials; warmups excluded')


def run_benchmark(examples, provenance, arms, out, research, *, repeats=5, warmups=1, resume=False):
    if repeats < 1 or warmups < 0:
        raise ValueError('invalid repeat/warmup count')
    out = safe_output(out, research)
    native_ready = initialize_timing_runtime()
    spec = dict(revision=REVISION, acceptance_policy_version='stage_relative_v2',
                provenance=provenance, repeats=repeats, warmups=warmups,
                arms={k: dict(checkpoint_id=v['checkpoint_id'], checkpoint_hash=v['checkpoint_hash'],
                              branch=v['branch'], scope=v['scope'], config=v['config'].to_dict()) for k, v in arms.items()},
                time_scope='imported process per-system cold constructor+solve wall time; process startup/checkpoint load excluded',
                included_costs='setup, NN generation, decisions, solve, rejected attempts and recovery',
                environment=hardware_environment(), native_library_available=native_ready,
                process_initialization='imports, checkpoint loading, existing native-library loading excluded; no compilation/autotune',
                no_training=True)
    manifest = out / 'run_manifest.json'
    if manifest.exists():
        previous = json.loads(manifest.read_text())
        if not resume: raise FileExistsError('Use a new output directory, or --resume with the identical inputs')
        if previous != json_safe(spec): raise ValueError('Resume input/config/version/environment signature mismatch')
    else:
        if resume: raise FileNotFoundError('No incomplete run manifest to resume')
        write_json(manifest, spec)
    rows = []; rawdir = out / 'cases'; rawdir.mkdir(exist_ok=True)
    for index, e in enumerate(examples):
        casefile = rawdir / f'{index:04d}.json'
        if resume and casefile.exists():
            row = json.loads(casefile.read_text())
            if row['example'] != json_safe(e.manifest()): raise ValueError('Resume case mismatch')
            if set(row['runs']) != set(arms) or any(len(r) != repeats for r in row['runs'].values()):
                raise ValueError('Incomplete or inconsistent saved case')
            for name, runs in row['runs'].items():
                arm = arms[name]
                for run in runs:
                    if (run.get('measurement_config') != arm['config'].to_dict()
                            or run.get('operator_digest') != e.digest
                            or run.get('checkpoint_id') != arm['checkpoint_id']
                            or run.get('requested_branch') != arm['branch']):
                        raise ValueError('Resume saved run input/config/branch signature mismatch')
        else:
            for _ in range(warmups):
                for v in arms.values(): measured(e, v['model'], v['config'])
            runs = {k: [] for k in arms}; execution_order = []
            rng = np.random.default_rng(1007 + index)
            for rep in range(repeats):
                order = rng.permutation(list(arms)).tolist(); execution_order.append(order)
                for name in order:
                    v = arms[name]; run = measured(e, v['model'], v['config'])
                    run.update(repeat=rep, checkpoint_id=v['checkpoint_id'], requested_branch=v['branch'])
                    runs[name].append(run)
            row = dict(example=e.manifest(), runs=runs, execution_order=execution_order)
            write_json(casefile, row)
        rows.append(row)
        write_json(out / 'progress.json', dict(status='running', completed_cases=len(rows), total=len(examples)))
        print(f'[no training] measured {len(rows)}/{len(examples)}: {e.name}', flush=True)
    result = aggregate_comparison(rows, arms)
    result.update(provenance=provenance, no_training=True, final_certificate_modified=False)
    write_json(out / 'raw_results.json', rows); write_json(out / 'comparison.json', result)
    with (out / 'comparison.csv').open('w', newline='') as stream:
        if result['table']:
            writer = csv.DictWriter(stream, fieldnames=list(result['table'][0])); writer.writeheader()
            for row in result['table']:
                writer.writerow({k: json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else v for k, v in row.items()})
    write_json(out / 'branch_statistics.json', [dict(case_id=r['case_id'], arm=r['arm'],
        branch=r['branch'], setup_seconds=r['setup_seconds'], total_seconds=r['total_seconds'],
        counters=r['counters_sum_all_repeats']) for r in result['table']])
    write_json(out / 'progress.json', dict(status='complete', completed_cases=len(rows), total=len(examples)))
    return result


def make_arm(checkpoint, cfg, branch, scope):
    if checkpoint is None:
        return dict(model=None, checkpoint_id='pure_classical', checkpoint_hash=None,
                    config=cfg, branch=branch, scope=scope)
    path = Path(checkpoint).resolve()
    return dict(model=Components.load(path), checkpoint_id=str(path), checkpoint_hash=digest_file(path),
                config=cfg, branch=branch, scope=scope)


def benchmark_main(argv=None):
    import argparse
    p = argparse.ArgumentParser(description='No training: saved candidates versus original fixed classical; diagnostic only.')
    p.add_argument('--research-dir', default='artifacts/my_v6_7_research')
    p.add_argument('--output-dir', default='artifacts/my_v6_7_limited_fix/direct')
    p.add_argument('--split', choices=['smoke', 'tune', 'audit'], default='smoke')
    p.add_argument('--limit', type=int); p.add_argument('--sizes', help='comma separated sizes for new smoke set only')
    p.add_argument('--repeats', type=int, default=5); p.add_argument('--warmups', type=int, default=1)
    p.add_argument('--checkpoint', help='Compare all four branches using this one checkpoint')
    p.add_argument('--branches', default='C,H_S,H_P,H_SP')
    p.add_argument('--joint-ablations', action='store_true')
    p.add_argument('--adaptive-checkpoint', help='Add calibrated policy in research and production modes')
    p.add_argument('--resume', action='store_true')
    args = p.parse_args(argv)
    research, settings, cfg = read_settings(args.research_dir)
    sizes = [int(n) for n in args.sizes.split(',')] if args.sizes else None
    examples, provenance = diagnostic_cases(research, settings, args.split, args.limit, sizes)
    arms = {'classical': make_arm(None, forced_config(cfg, 'C'), 'C', 'pure classical fixed baseline')}
    skipped = []
    if args.checkpoint:
        for branch in args.branches.split(','):
            if branch not in BRANCHES: p.error('branches must be C,H_S,H_P,H_SP')
            if branch != 'C': arms[branch] = make_arm(args.checkpoint, forced_config(cfg, branch), branch, 'forced component + safety')
    else:
        final = research / 'checkpoint_v6_7_final.pt'
        arms['original_final_adaptive'] = make_arm(final, replace(cfg, mode='research'), 'auto', 'original final policy research diagnostic')
        arms['original_final_production'] = make_arm(final, cfg, 'auto', 'original final production policy')
        for stage, branch in (('smoother', 'H_S'), ('transfer', 'H_P'), ('joint', 'H_SP')):
            path = research / stage / 'candidate.pt'
            if path.exists(): arms[stage + '_' + branch] = make_arm(path, forced_config(cfg, branch), branch, 'forced component + safety')
            else: skipped.append(dict(stage=stage, reason='candidate checkpoint missing', path=str(path)))
        if args.joint_ablations and (research / 'joint/candidate.pt').exists():
            for branch in ('H_S', 'H_P'):
                arms['joint_' + branch] = make_arm(research / 'joint/candidate.pt', forced_config(cfg, branch), branch, 'forced component + safety ablation')
    if args.adaptive_checkpoint:
        for mode in ('research', 'production'):
            model = Components.load(args.adaptive_checkpoint)
            calibration_cfg = model.metadata.get('limited_refit_config')
            if not calibration_cfg: raise ValueError('Checkpoint lacks limited_refit_config from policy refit')
            pcfg = AdaptiveConfig.from_dict(calibration_cfg)
            if pcfg.mg != cfg.mg: raise ValueError('Refit baseline configuration differs from research baseline')
            arms['refit_' + mode] = make_arm(args.adaptive_checkpoint, replace(pcfg, mode=mode), 'auto', 'refitted policy; certificate remains unchanged')
    provenance['missing_arms'] = skipped
    result = run_benchmark(examples, provenance, arms, args.output_dir, research,
                           repeats=args.repeats, warmups=args.warmups, resume=args.resume)
    print(json.dumps(result['summary'], ensure_ascii=False, indent=2))
    print('NO TRAINING. No independent certificate issued. Output:', Path(args.output_dir).resolve())
